### ISSUE TITLE
Question: Have you tried wrap the SPA with capacitor to make it also mobile app?

### ISSUE THREAD

**Issue by fro-profesional** [ccssmnn/relaxed-spa#2]
Question: Have you tried wrap the SPA with [capacitor](https://capacitorjs.com/) to make it also mobile app?
Do you think it might work?

**Comment by carlassmann** [comment]
Hey! Thank you for checking out this repo.

I've tried to initialize a Capacitor project and ran `deno run npm:@capacitor/cli init` and got:

```
✅ Granted all read access.
✅ Granted all env access.
error: Uncaught Error: Not implemented: See https://github.com/denoland/deno_std/issues/1436
    at notImplemented (ext:deno_node/_utils.ts:7:11)
    at Object.userInfo (ext:deno_node/os.ts:210:5)
    at getShell (file:///Users/carlassmann/Library/Caches/deno/npm/registry.npmjs.org/@ionic/utils-terminal/2.3.4/dist/info.js:15:26)
    at Object.<anonymous> (file:///Users/carlassmann/Library/Caches/deno/npm/registry.npmjs.org/@ionic/utils-terminal/2.3.4/dist/info.js:35:12)
    at Object.<anonymous> (file:///Users/carlassmann/Library/Caches/deno/npm/registry.npmjs.org/@ionic/utils-terminal/2.3.4/dist/info.js:41:4)
    at Module._compile (ext:deno_node/01_require.js:968:34)
    at Object.Module._extensions..js (ext:deno_node/01_require.js:1001:10)
    at Module.load (ext:deno_node/01_require.js:879:32)
    at Function.Module._load (ext:deno_node/01_require.js:713:12)
    at Module.require (ext:deno_node/01_require.js:901:19)
```

Unfortunately, there are many useful tools in the frontend space, that are tightly bound to node and Capacitor seems to be one of them.

To use the SPA you're creating with the approach of this repo, you could:
- add another deno script, that builds the assets and stores them in a folder (e.g. `dist`)
- create a capacitor project using node & npm (you might only need the capacitor CLI)
- tell capacitor where to find the assets when building your native apps
- tell your app where to find your backend

Once set up, you should be able to develop your App in deno + native parts in the respective native projects capacitor will set up for you

**Comment by fro-profesional** [comment]
Thanks for your response! closing the issue will try your suggestions, thanks!
